CREATE TABLE IF NOT EXISTS users(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(50) NOT NULL UNIQUE CHECK(LENGTH(username)>=2 AND LENGTH(username)<=50),
email VARCHAR(50) NOT NULL,
password VARCHAR(100) NOT NULL,
created_date DATE NOT NULL,
last_updated_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS roles(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL
);


CREATE TABLE IF NOT EXISTS user_roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT user_role_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT role_user_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);